### ISSUE TITLE
Debugger didn't start when try to redebug the same war package to the same jetty server

### ISSUE THREAD

**Issue by songkaiape** [SummerSun/vscode-jetty#15]
repro steps:
1. create a jetty server
2. right click a war package to debug on the server
3. click disconnect on the debugger toolbar
4. right click the war package to debug again
Expect: the debugger start 
Actual: the debugger didn't start

**Comment by SummerSun** [comment]
This is truly an scenario that we didn't think of.

we are watching the whole java process after starting run/debug the server, and we know nothing when debug session disconnect. Seems we should watch the debug session also.

**Comment by songkaiape** [comment]
repro on windows
