### ISSUE TITLE
[Windows]War package still exist in the tree view after deleted on a running jetty server . But actually it has been deleted

### ISSUE THREAD

**Issue by songkaiape** [SummerSun/vscode-jetty#17]
repro steps:

1. create a jetty server
2. right click a war package to run on the server
3. delete the war package in the server tree view
Expect: the war package disappeared in the tree view
Actual: the war package still existed until stop the jetty server

**Comment by SummerSun** [comment]
It is by design. When the server is running, we could no operate its file structure until it stops.

**Comment by SummerSun** [comment]
are you view the war packge in browser before you try to delete it? if so, the resource is locked by explorer, you could not delete if until you close the browser tab or stop the server.

**Comment by songkaiape** [comment]
I verified this issue again, I found it still repro even I didn't open any browse page.
