### ISSUE TITLE
[Linux] open in browser failed with error

### ISSUE THREAD

**Issue by songkaiape** [SummerSun/vscode-jetty#6]
repro step:
1. create a jetty server
2. run a war package to it
3. right click the package and select open in browser
Expect: a browser will open
Actual: an error occured
![image](https://user-images.githubusercontent.com/4318793/39609381-2b3d351c-4f7b-11e8-840c-d29a46fb48e8.png)

**Comment by SummerSun** [comment]
Did not repro it in linux. An error occured, means the behavior is not correct, or there are errors in developer tools? What is the behavior? And also, you need a standard war package for jetty to do the testing.

**Comment by songkaiape** [comment]
chmod +x /home/lekhnath/.vscode/extensions/Shan.code-settings-sync-2.8.0/node_modules/opn/xdg-open 
Not repro after add permission for opn folder
