### ISSUE TITLE
The page didn't show expected content after deploy to jetty server

### ISSUE THREAD

**Issue by songkaiape** [SummerSun/vscode-jetty#7]
repro steps:
1. create a jetty server
2. deploy a war package built from 
https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-web-jsp
https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-jetty-jsp
3.run the package on the jetty server
4. open the browser

Expect: the page will show like below
![image](https://user-images.githubusercontent.com/4318793/39609498-015fdb22-4f7c-11e8-8ae5-602824b86270.png)
Actual: 
![image](https://user-images.githubusercontent.com/4318793/39609503-0ac3a73e-4f7c-11e8-8ee3-f6d95cb9cb1e.png)
And if we reveal the folder there is nothing in the folder. Usually it will contain some files extracted from the war package

**Comment by SummerSun** [comment]
>A directory called example/ is deployed as a standard web application if it contains a WEB-INF/ subdirectory, otherwise it is deployed as context of static content. 

https://www.eclipse.org/jetty/documentation/current/quickstart-deploying-webapps.html

You could use a standard war package example to do the testing.
