### ISSUE TITLE
Server failed to start on the first time after click run on jetty server

### ISSUE THREAD

**Issue by songkaiape** [SummerSun/vscode-jetty#9]
1. create a new jetty server
2. right click on a war package and select run on jetty server

Expect: the server will start
Actual: the server start for a little while and change to closed state. This only repro on the first time when we run war package on jetty server.
![image](https://user-images.githubusercontent.com/4318793/39609595-ac61c260-4f7c-11e8-91be-bb92095d7082.png)

**Comment by SummerSun** [comment]
Did not repro in my side, could you please share more info about this issue?

**Comment by songkaiape** [comment]
doesn't repro after change to jetty 9.49, close this issue
